#
# Config file (consumed by Snakemake) which specifies parameters for the exogenous-driven land transport (toy) model
#


scenario:
  clusters:
    - 37


snapshots:
  start: "2013-01-01"
  end: "2013-12-31"


sector:
  bev_dsm_restriction_value: 0.75  #Set to 0 for no restriction on BEV DSM
  bev_dsm_restriction_time: 7  #Time at which SOC of BEV has to be dsm_restriction_value
  transport_heating_deadband_upper: 20.
  transport_heating_deadband_lower: 15.
  ICE_lower_degree_factor: 0.375  #in per cent increase in fuel consumption per degree above deadband
  ICE_upper_degree_factor: 1.6
  EV_lower_degree_factor: 0.98
  EV_upper_degree_factor: 0.63
  bev_dsm: true #turns on EV battery
  bev_availability: 0.5  #How many cars do smart charging
  bev_energy: 0.05  #average battery size in MWh
  bev_charge_efficiency: 0.9  #BEV (dis-)charging efficiency
  bev_plug_to_wheel_efficiency: 0.2 #kWh/km from EPA https://www.fueleconomy.gov/feg/ for Tesla Model S
  bev_charge_rate: 0.011 #3-phase charger with 11 kW
  bev_avail_max: 0.95
  bev_avail_mean: 0.8
  v2g: true #allows feed-in to grid from EV battery


  land_transport_electric_share:
    2020: 0.1
    2030: 0.25
    2040: 0.6
    2050: 1.0

  land_transport_ice_share:
    2020: 0.9
    2030: 0.75
    2040: 0.4
    2050: 0.0


  transport_internal_combustion_efficiency: 0.3
  agriculture_machinery_electric_share: 0
  agriculture_machinery_oil_share: 1
  agriculture_machinery_fuel_efficiency: 0.7 # fuel oil per use
  agriculture_machinery_electric_efficiency: 0.3 # electricity per use
  MWh_MeOH_per_MWh_H2: 0.8787 # in LHV, source: DECHEMA (2017): Low carbon energy and feedstock for the European chemical industry , pg. 64.
  MWh_MeOH_per_tCO2: 4.0321 # in LHV, source: DECHEMA (2017): Low carbon energy and feedstock for the European chemical industry , pg. 64.
  MWh_MeOH_per_MWh_e: 3.6907 # in LHV, source: DECHEMA (2017): Low carbon energy and feedstock for the European chemical industry , pg. 64.
  time_dep_hp_cop: true #time dependent heat pump coefficient of performance
  solar_thermal: true
  solar_cf_correction: 0.788457  # =  >>> 1/1.2683
  marginal_cost_storage: 0. #1e-4
  co2_sequestration_potential: 200  #MtCO2/a sequestration potential for Europe
  co2_sequestration_cost: 10   #EUR/tCO2 for sequestration of CO2
  co2_network: false
  cc_fraction: 0.9  # default fraction of CO2 captured with post-combustion capture
  electricity_distribution_grid: true
  electricity_distribution_grid_cost_factor: 1.0  #multiplies cost in data/costs.csv
  electricity_grid_connection: true  # only applies to onshore wind and utility PV

